version: '3.8'

services:
  user_managment_service:
    image: akayti/server:v1
    container_name: api_gateway_nginx
    ports:
      - '8000:80'
    volumes:
      - ./src:/var/www/html:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    networks:
      - shared_network

  php:
    image: akayti/php:v1
    container_name: api_gateway
    volumes:
      - ./src:/var/www/html:delegated
    networks:
      - shared_network

  composer: 
    image: akayti/composer:v1
    volumes:
      - ./src:/var/www/html
    networks:
      - shared_network
    depends_on:
      - php

  artisan:
    image: akayti/php:v1
    volumes:
      - ./src:/var/www/html
    entrypoint: ['php', '/var/www/html/artisan']
    networks:
      - shared_network
    depends_on:
      - php

  npm:
    image: node:14
    working_dir: /var/www/html
    command: ['npm', 'install']
    volumes:
      - ./src:/var/www/html
    networks:
      - shared_network
    depends_on:
      - php

networks:
  shared_network:
    external: true
